linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gofumpt
    - exhaustivestruct
    - exhaustruct
    - wrapcheck
    - goerr113
    - gci
    - godox
    - varnamelen
    - golint
    - ireturn
    - nosnakecase
linters-settings:
  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: snake
        yaml: kebab
  wsl:
    # See https://github.com/bombsimon/wsl/blob/master/doc/configuration.md for
    # documentation of available settings.
    allow-assign-and-anything: false
    allow-assign-and-call: true
    allow-cuddle-declarations: false
    allow-multiline-assign: true
    allow-separated-leading-comment: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    force-short-decl-cuddling: false
    strict-append: true
  godox:
    keywords:
      - BUG
      - FIX
      - FIXME
      - TODO
      - bug
      - fixme
      - todo
      - fix
  gomnd:
    settings:
      mnd:
        checks: [ argument,case,condition,operation,return,assign ]
        ignored-numbers: [ 1,2,3,10,64,512 ]
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 75
  revive:
    rules:
      - name: var-naming
        disabled: true
  stylecheck:
    checks: [ "all", "-ST1003" ]
run:
  modules-download-mode: vendor
  skip-dirs:
    - "api"
  skip-files:
    - "_test.go"
